version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password
      POSTGRES_DB: covid
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    command: >
      sh -c "flask db upgrade &&
             flask run --host=0.0.0.0 &&
             sleep 10 &&
             flask load-data"
    restart: on-failure
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
